### ISSUE TITLE
[1.19.2] Centered glazed terracotta blocks output one slab when using a stonecutter.

### ISSUE THREAD

**Issue by TheBrewingMiner** [Lethosos/Glazed-Resymmetry#4]
It appears to only be the case with the centered blocks. Other blocks output the quantity expected. I'm on 1.19.2, with Forge 43.2.21

<img width="648" alt="Screenshot 2024-02-01 at 8 26 53 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/6662ab76-a685-44e8-934c-e48fadbe7e2c">
<img width="272" alt="Screenshot 2024-02-01 at 8 27 28 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/b8957f0b-84ae-448d-ae57-d7948bf33f68">
<img width="269" alt="Screenshot 2024-02-01 at 8 28 01 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/2dd1355a-5967-4b29-bbf3-c848a1ca8877">
<img width="266" alt="Screenshot 2024-02-01 at 8 28 20 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/57a7118f-ba54-4c69-a938-335ea622ac0d">
<img width="266" alt="Screenshot 2024-02-01 at 8 28 36 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/1eedaa49-6718-499f-8df5-4624b0975ad6">
<img width="265" alt="Screenshot 2024-02-01 at 8 28 56 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/261f2b42-ba88-4ecb-b950-0de0e545d827">
<img width="263" alt="Screenshot 2024-02-01 at 8 29 18 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/79e99098-d1c3-4785-ad4d-c09ddc5f722c">
<img width="263" alt="Screenshot 2024-02-01 at 8 29 35 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/9b1c2ae9-f82f-4b4b-a80d-4273f975dcea">
<img width="268" alt="Screenshot 2024-02-01 at 8 29 48 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/a127666e-6025-499a-b81d-e149fc80f497">
<img width="265" alt="Screenshot 2024-02-01 at 8 30 04 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/1b57fa60-baaa-4fe6-b520-5c379fce2124">
<img width="268" alt="Screenshot 2024-02-01 at 8 30 16 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/5172b35a-85ee-40a7-b408-0b9c1a166985">
<img width="264" alt="Screenshot 2024-02-01 at 8 30 36 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/84f6d07e-3ee5-4fa0-9635-403379c4b88a">
<img width="263" alt="Screenshot 2024-02-01 at 8 30 53 PM" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/0e538491-6f17-473f-9642-dd578a09c55c">

**Comment by Lethosos** [comment]
Been sick for quite awhile, but thank you for notifying me.

**Comment by Lethosos** [comment]
Hrm. Did you actually run it through the Stonecutter itself? These are JEI recipe outputs, as actual crafting gives me two slabs per block.

**Comment by TheBrewingMiner** [comment]
Yes, I used the stonecutter for awhile until I noticed the issue. When I realized, I used JEI to check through and found it happening for all centered terracotta blocks. Here's an example: https://youtu.be/yWRW_jrahhA

I should also add that the version I am using, on top of 1.19.2 FML 43.2.21 is 1.4
<img width="625" alt="Glazed ReSymm 1 4" src="https://github.com/Lethosos/Glazed-Resymmetry/assets/130880104/8a09c08e-629d-4710-a191-886f6eb07cd7">

**Comment by Lethosos** [comment]
Hrm. I'm actually stumped, as this looks like recipes just stop working after a while. Which is NOT intended behavior all around. I'll keep an eye out and do some more testing as soon as possible.

**Comment by Lethosos** [comment]
Okay, can you run this version, see if it outputs as intended?

http://www.biolante.org/Stuff/glazed-resymmetry-1_19_2-1.5.jar

**Comment by TheBrewingMiner** [comment]
I've just tested it, and the stonecutter appears to output as intended. 

Although, now the lime terracotta block family has lost its crafting table recipes (except the conversion from slabs to full-blocks), and so has brown glazed terracotta slabs (also except for slabs to full-blocks).

**Comment by Lethosos** [comment]
O_o

I honestly don't know why that's happening to you now.

**Comment by TheBrewingMiner** [comment]
I'm not sure either. I started a fresh instance with only Glazed Resymmetry on (the .jar you sent)
