### ISSUE TITLE
[1.19.2] Double-slab blocks do not drop two slabs upon breaking, only one.

### ISSUE THREAD

**Issue by TheBrewingMiner** [Lethosos/Glazed-Resymmetry#5]
When two slabs are placed onto each other, the resulting block does not drop two slabs when mined. Instead, it only drops one. The video attached also highlights missing crafting table recipes for slab forms. In particular, the crafting table recipes appear to be missing for light gray, gray, and lime terracotta families.

https://youtu.be/n93_uRKpUNg

**Comment by Lethosos** [comment]
Been sick for quite awhile, but thank you for notifying me.

**Comment by Lethosos** [comment]
Okay, loot tables for slabs weren't done correctly as I originally thought. Went ahead and wrote out a new loot table for each with the appropriate checks in place.

I'll push an update soon.
